# Generated by Django 3.1.5 on 2021-01-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo_description', models.TextField()),
                ('photo', models.ImageField(default='image.jpg', upload_to='images/')),
                ('photo_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.category')),
                ('photo_location', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.location')),
            ],
        ),
    ]
